prep-html-script-tag exercise- Kayla Cloud
kaylacloud/javascript-prep-0124-code-solutions pull request #3
Opened 2024-01-09 22:10 UTC by kaylacloud

<img width="790" alt="Screenshot 2024-01-09 at 1 41 48 PM" src="https://github.com/kaylacloud/javascript-prep-0124-code-solutions/assets/155405931/2bdbb7a2-1f8d-4746-9b9c-1fa7648fb7f8">

2024-01-09 23:11 UTC, Zhiwutian requested changes
one small update needed for completion!

2024-01-09 23:11 UTC, Zhiwutian commented on prep-html-script-tag/index.html
> +    <script> console.log ("I have added a script file via the src attribute!") </script>
This console.log should be in the main.js file.

2024-01-10 00:47 UTC, kaylacloud commented
<img width="794" alt="Screenshot 2024-01-09 at 4 41 38 PM" src="https://github.com/kaylacloud/javascript-prep-0124-code-solutions/assets/155405931/84d828df-6f03-4f44-8e4a-eb506a9cfaa1">

2024-01-10 02:21 UTC, Zhiwutian requested changes
One more update!

2024-01-10 02:21 UTC, Zhiwutian commented on prep-html-script-tag/main.js
> +console.log("I have added a script file via the src attribute!")
only the console log should be in this file. Js files don't have HTML in them

2024-01-12 00:14 UTC, kaylacloud commented
<img width="992" alt="Screenshot 2024-01-11 at 4 14 46 PM" src="https://github.com/kaylacloud/javascript-prep-0124-code-solutions/assets/155405931/47f457d6-0c12-44d9-8a47-4ebed8baf594">

2024-01-12 01:20 UTC, BrettAlbright approved these changes
👍🏼

2024-01-12 02:21 UTC, merged